// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Same precedence Next.js uses: .env.local (Vercel-pulled) wins over .env.
config({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations want a direct connection: DDL through Neon's pgbouncer pooler
    // is unreliable. At runtime lib/prisma.ts uses the pooled DATABASE_URL.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
