// Curated starter packs for the default use case: Russian speakers learning
// English. Packs are copied into a user's own sets, so editing a copy never
// affects the catalog.

export type PackLevel = "A1" | "A2" | "B1";

export interface StarterPack {
  slug: string;
  title: string;
  description: string;
  level: PackLevel;
  cards: { term: string; definition: string }[];
}

export const STARTER_PACKS: StarterPack[] = [
  {
    slug: "top-verbs",
    title: "Top English Verbs",
    description: "The most common verbs you'll meet everywhere",
    level: "A1",
    cards: [
      { term: "be", definition: "быть" },
      { term: "have", definition: "иметь" },
      { term: "do", definition: "делать" },
      { term: "say", definition: "говорить, сказать" },
      { term: "get", definition: "получать" },
      { term: "make", definition: "делать, создавать" },
      { term: "go", definition: "идти, ехать" },
      { term: "know", definition: "знать" },
      { term: "take", definition: "брать" },
      { term: "see", definition: "видеть" },
      { term: "come", definition: "приходить" },
      { term: "think", definition: "думать" },
      { term: "look", definition: "смотреть" },
      { term: "want", definition: "хотеть" },
      { term: "give", definition: "давать" },
      { term: "use", definition: "использовать" },
      { term: "find", definition: "находить" },
      { term: "tell", definition: "рассказывать" },
      { term: "ask", definition: "спрашивать" },
      { term: "work", definition: "работать" },
      { term: "feel", definition: "чувствовать" },
      { term: "try", definition: "пытаться" },
      { term: "leave", definition: "уходить, покидать" },
      { term: "call", definition: "звонить, звать" },
      { term: "need", definition: "нуждаться" },
      { term: "become", definition: "становиться" },
      { term: "mean", definition: "значить, иметь в виду" },
      { term: "keep", definition: "хранить, продолжать" },
      { term: "let", definition: "позволять" },
      { term: "begin", definition: "начинать" },
    ],
  },
  {
    slug: "irregular-verbs",
    title: "Irregular Verbs",
    description: "Key irregular verbs with all three forms",
    level: "A2",
    cards: [
      { term: "be — was/were — been", definition: "быть" },
      { term: "begin — began — begun", definition: "начинать" },
      { term: "break — broke — broken", definition: "ломать" },
      { term: "bring — brought — brought", definition: "приносить" },
      { term: "buy — bought — bought", definition: "покупать" },
      { term: "choose — chose — chosen", definition: "выбирать" },
      { term: "come — came — come", definition: "приходить" },
      { term: "do — did — done", definition: "делать" },
      { term: "drink — drank — drunk", definition: "пить" },
      { term: "eat — ate — eaten", definition: "есть" },
      { term: "fall — fell — fallen", definition: "падать" },
      { term: "find — found — found", definition: "находить" },
      { term: "fly — flew — flown", definition: "летать" },
      { term: "forget — forgot — forgotten", definition: "забывать" },
      { term: "get — got — got/gotten", definition: "получать" },
      { term: "give — gave — given", definition: "давать" },
      { term: "go — went — gone", definition: "идти" },
      { term: "know — knew — known", definition: "знать" },
      { term: "make — made — made", definition: "делать" },
      { term: "run — ran — run", definition: "бежать" },
      { term: "see — saw — seen", definition: "видеть" },
      { term: "speak — spoke — spoken", definition: "говорить" },
      { term: "take — took — taken", definition: "брать" },
      { term: "think — thought — thought", definition: "думать" },
      { term: "write — wrote — written", definition: "писать" },
    ],
  },
  {
    slug: "essential-nouns",
    title: "Essential Nouns",
    description: "Everyday nouns for people, places and things",
    level: "A1",
    cards: [
      { term: "time", definition: "время" },
      { term: "year", definition: "год" },
      { term: "people", definition: "люди" },
      { term: "way", definition: "путь, способ" },
      { term: "day", definition: "день" },
      { term: "man", definition: "мужчина, человек" },
      { term: "woman", definition: "женщина" },
      { term: "child", definition: "ребёнок" },
      { term: "world", definition: "мир" },
      { term: "life", definition: "жизнь" },
      { term: "hand", definition: "рука (кисть)" },
      { term: "eye", definition: "глаз" },
      { term: "place", definition: "место" },
      { term: "work", definition: "работа" },
      { term: "week", definition: "неделя" },
      { term: "house", definition: "дом" },
      { term: "family", definition: "семья" },
      { term: "friend", definition: "друг" },
      { term: "water", definition: "вода" },
      { term: "food", definition: "еда" },
      { term: "money", definition: "деньги" },
      { term: "city", definition: "город" },
      { term: "country", definition: "страна" },
      { term: "school", definition: "школа" },
      { term: "question", definition: "вопрос" },
      { term: "answer", definition: "ответ" },
      { term: "word", definition: "слово" },
      { term: "book", definition: "книга" },
      { term: "night", definition: "ночь" },
      { term: "morning", definition: "утро" },
    ],
  },
  {
    slug: "common-adjectives",
    title: "Common Adjectives",
    description: "Adjectives to describe almost anything",
    level: "A1",
    cards: [
      { term: "good", definition: "хороший" },
      { term: "bad", definition: "плохой" },
      { term: "new", definition: "новый" },
      { term: "old", definition: "старый" },
      { term: "big", definition: "большой" },
      { term: "small", definition: "маленький" },
      { term: "long", definition: "длинный" },
      { term: "short", definition: "короткий" },
      { term: "high", definition: "высокий" },
      { term: "low", definition: "низкий" },
      { term: "early", definition: "ранний" },
      { term: "late", definition: "поздний" },
      { term: "easy", definition: "лёгкий, простой" },
      { term: "difficult", definition: "трудный" },
      { term: "important", definition: "важный" },
      { term: "beautiful", definition: "красивый" },
      { term: "happy", definition: "счастливый" },
      { term: "sad", definition: "грустный" },
      { term: "strong", definition: "сильный" },
      { term: "weak", definition: "слабый" },
      { term: "fast", definition: "быстрый" },
      { term: "slow", definition: "медленный" },
      { term: "hot", definition: "горячий, жаркий" },
      { term: "cold", definition: "холодный" },
      { term: "expensive", definition: "дорогой" },
    ],
  },
  {
    slug: "everyday-phrases",
    title: "Everyday Phrases",
    description: "Short phrases for daily conversation",
    level: "A2",
    cards: [
      { term: "How are you?", definition: "Как дела?" },
      { term: "Nice to meet you", definition: "Приятно познакомиться" },
      { term: "What time is it?", definition: "Который час?" },
      { term: "I don't understand", definition: "Я не понимаю" },
      { term: "Could you repeat that?", definition: "Не могли бы вы повторить?" },
      { term: "How much does it cost?", definition: "Сколько это стоит?" },
      { term: "Where is the restroom?", definition: "Где туалет?" },
      { term: "I'm looking for…", definition: "Я ищу…" },
      { term: "Can you help me?", definition: "Вы можете мне помочь?" },
      { term: "I'd like to order", definition: "Я хотел(а) бы заказать" },
      { term: "Excuse me", definition: "Извините (обращение)" },
      { term: "I'm sorry", definition: "Простите, мне жаль" },
      { term: "You're welcome", definition: "Пожалуйста (в ответ на спасибо)" },
      { term: "See you later", definition: "До встречи" },
      { term: "Have a nice day", definition: "Хорошего дня" },
      { term: "What does it mean?", definition: "Что это значит?" },
      { term: "I agree", definition: "Я согласен (согласна)" },
      { term: "Of course", definition: "Конечно" },
      { term: "No problem", definition: "Без проблем" },
      { term: "Take care", definition: "Береги себя" },
    ],
  },
  {
    slug: "travel-city",
    title: "Travel & City",
    description: "Getting around: transport, directions, sightseeing",
    level: "A2",
    cards: [
      { term: "airport", definition: "аэропорт" },
      { term: "train station", definition: "вокзал" },
      { term: "ticket", definition: "билет" },
      { term: "return ticket", definition: "обратный билет" },
      { term: "luggage", definition: "багаж" },
      { term: "passport", definition: "паспорт" },
      { term: "customs", definition: "таможня" },
      { term: "departure", definition: "отправление, вылет" },
      { term: "arrival", definition: "прибытие" },
      { term: "timetable", definition: "расписание" },
      { term: "map", definition: "карта" },
      { term: "street", definition: "улица" },
      { term: "square", definition: "площадь" },
      { term: "bridge", definition: "мост" },
      { term: "crossroads", definition: "перекрёсток" },
      { term: "museum", definition: "музей" },
      { term: "hotel", definition: "гостиница" },
      { term: "booking", definition: "бронирование" },
      { term: "sightseeing", definition: "осмотр достопримечательностей" },
      { term: "guided tour", definition: "экскурсия с гидом" },
    ],
  },
  {
    slug: "phrasal-verbs",
    title: "Phrasal Verbs",
    description: "The phrasal verbs you can't avoid in real English",
    level: "B1",
    cards: [
      { term: "give up", definition: "сдаваться, бросать" },
      { term: "look for", definition: "искать" },
      { term: "look after", definition: "присматривать за" },
      { term: "find out", definition: "выяснять, узнавать" },
      { term: "carry on", definition: "продолжать" },
      { term: "put off", definition: "откладывать" },
      { term: "turn on", definition: "включать" },
      { term: "turn off", definition: "выключать" },
      { term: "pick up", definition: "подбирать; забирать" },
      { term: "get along", definition: "ладить" },
      { term: "run out of", definition: "заканчиваться (о запасах)" },
      { term: "come across", definition: "случайно натыкаться на" },
      { term: "set up", definition: "основывать; настраивать" },
      { term: "take off", definition: "взлетать; снимать (одежду)" },
      { term: "break down", definition: "ломаться" },
      { term: "bring up", definition: "воспитывать; поднимать (тему)" },
      { term: "call off", definition: "отменять" },
      { term: "figure out", definition: "разобраться, понять" },
      { term: "show up", definition: "появляться, приходить" },
      { term: "work out", definition: "тренироваться; получаться" },
    ],
  },
  {
    slug: "work-career",
    title: "Work & Career",
    description: "Vocabulary for the office, interviews and career talk",
    level: "B1",
    cards: [
      { term: "salary", definition: "зарплата" },
      { term: "job interview", definition: "собеседование" },
      { term: "CV / resume", definition: "резюме" },
      { term: "employer", definition: "работодатель" },
      { term: "employee", definition: "сотрудник" },
      { term: "colleague", definition: "коллега" },
      { term: "promotion", definition: "повышение" },
      { term: "deadline", definition: "крайний срок" },
      { term: "meeting", definition: "совещание" },
      { term: "skill", definition: "навык" },
      { term: "experience", definition: "опыт" },
      { term: "department", definition: "отдел" },
      { term: "schedule", definition: "график, расписание" },
      { term: "task", definition: "задача" },
      { term: "responsibility", definition: "ответственность" },
      { term: "to hire", definition: "нанимать" },
      { term: "to fire", definition: "увольнять" },
      { term: "to negotiate", definition: "вести переговоры" },
      { term: "business trip", definition: "командировка" },
      { term: "day off", definition: "выходной" },
    ],
  },
];
